export const CONFIG = {
	API_URL: "https://pokeapi.co/api/v2",
	POKEMON_EXPERIENCE_MULTIPLIER: 1.15,
	POKEMON_HEALTH_MULTIPLIER: 1.15,
	POKEMON_ATTACK_MULTIPLIER: 1.15,
	POKEMON_DEFENSE_MULTIPLIER: 1.15,
	POKEMON_SPEED_MULTIPLIER: 1.15,
	POKEMON_REGEN_MULTIPLIER: 1.15,
};
