export const CONFIG = {
	API_URL: "https://pokeapi.co/api/v2",
	BASE_EXPERIENCE: 100,
	POKEMON_EXPERIENCE_MULTIPLIER: 1.15,
	POKEMON_HEALTH_MULTIPLIER: 1.15,
	POKEMON_ATTACK_MULTIPLIER: 1.15,
	POKEMON_DEFENSE_MULTIPLIER: 1.15,
	POKEMON_SPEED_MULTIPLIER: 1.15,
	POKEMON_REGEN_MULTIPLIER: 1.15,
	PLAYER_INITIAL_ATTACK: 10,
};
